development:
  adapter: mysql2
  encoding: utf8
  database: rota
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock
  host: localhost
 
test: 
  adapter: sqlite3 
  database: db/test.sqlite3 
  pool: 5 
  timeout: 5000

production: 
  adapter: mysql2
  encoding: utf8
  reconnect: true
  host:
  database: rota_production
  pool: 5
  username: root
  password:


